server:
  port: 8889
  servlet:
    session:
      timeout: 72000

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.88.103:3306/graduation?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '@Fan201314'

    #解决连接8小时特性
    dbcp2:
      test-while-idle: true  #验证连接的有效性
      #获取连接时候验证，会影响性能
      test-on-borrow: true
      validation-query: select 1
      #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
      time-between-eviction-runs-millis: 300000
      #连接池空闲连接的有效时间 ，设置30分钟
      min-evictable-idle-time-millis: 1800000


  #时区设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8

  #文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB

#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  #加载Mybatis映射文*
  mapper-locations: classpath*:mapper/*Mapper.xml

## File Storage Properties
# Please change this to the path where you want the uploaded files to be stored.
#file.path=G:\\file