server:
  port: 8889
  servlet:
    session:
      timeout: 86400s

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.88.103:3306/graduation?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '@Fan201314'

  #时区设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8

  #文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB

#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  #加载Mybatis映射文*
  mapper-locations: classpath*:mapper/*Mapper.xml

## File Storage Properties
# Please change this to the path where you want the uploaded files to be stored.
#file.path=G:\\file