server:
  port: 8889
  servlet:
    session:
      timeout: 72000

spring:
  main:
    allow-bean-definition-overriding: true    #当遇到同样名字的时候，是否允许覆盖注册

  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.24.88.103:3306/graduation?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '@Fan201314'

    #解决连接8小时特性
    dbcp2:
      test-while-idle: true  #验证连接的有效性
      #获取连接时候验证，会影响性能
      test-on-borrow: true
      validation-query: select 1
      #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
      time-between-eviction-runs-millis: 300000
      #连接池空闲连接的有效时间 ，设置30分钟
      min-evictable-idle-time-millis: 1800000
      min-idle: 5                         # 数据库连接池的最小维持连接数
      initial-size: 5                     # 初始化连接数
      max-total: 5                        # 最大连接数
      max-wait-millis: 150                # 等待连接获取的最大超时时间
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

  #时区设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8

  #文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB

  #redis配置
  reids:
    #数据库索引
    database: 0
    #redis服务器地址
    host: 175.24.88.103
    #服务器连接端口
    port: 6379
    #服务器连接密码（默认为空）
    password:
    #连接池最大连接数（使用负值表示没有限制）
    maxActive: 8
    #连接池最大阻塞等待时间（使用负值表示没有限制）
    maxWait: -1
    #连接池中最大空闲连接
    maxIdle: 8
    #连接池中最小空闲连接
    minIdle: 0
    #连接超时时间（毫秒）
    timeout: 0

  security:
    user:
      name: admin
      password: admin

    ignored: /swagger-ui.html,/swagger-ui.html/*,/webjars/**,/error,/swagger-resources/**


#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  #加载Mybatis映射文*
  mapper-locations: classpath*:mapper/*Mapper.xml

## File Storage Properties
# Please change this to the path where you want the uploaded files to be stored.
#file.path=G:\\file


#logging:
#  level:
#    com:
#      fanr:
#        graduation:
#          mapper: debug


